Repository Lambda-School-Labs/trashpanda-be, pull requests merged in 2020-02, with the labels that each got.

#37 Feature/31 add search locations
  src/datasources/earth.js
  src/resolvers.js
  src/schema.js
Labels: feature

#38 Feature/30
  database/migrations/20200201103833_postal_code_implementation.js
  database/migrations/20200201105116_postal_codes_table.js
  database/models/postal_codes-model.js
  src/datasources/earth.js
  src/resolvers.js
  src/resolvers.test.js
  src/schema.js
Labels: feature

#39 Add optional material_id param for location search
  package.json
  src/datasources/earth.js
  src/resolvers.js
  src/schema.js
Labels: feature

#43 Add code climate badges
  README.md
Labels: documentation

#42 Updates bulk of Read Me to be accurate with our code
  README.md
Labels: documentation

#44 Feature/29
  .env-example
  database/dbConfig.js
  database/models/__mocks__/materials-model.js
  knexfile.js
  package.json
  src/__tests__/mock_data/mockSchemaResponses.js
  src/__tests__/schema.js
  src/datasources/__tests__/earth.js
  src/datasources/__tests__/mock_data/mockEarthResponses.js
  src/datasources/earth.js
  src/index.js
  src/resolvers.test.js
Labels: feature

#47 Bug/46
  src/__tests__/mock_data/mockClientQueries.js
  src/__tests__/mock_data/mockSchemaResponses.js
  src/__tests__/schema.js
  src/datasources/earth.js
Labels: bug

#48 Add tests for earth API
  database/models/__mocks__/postal_codes-model.js
  src/datasources/__tests__/earth.js
  src/datasources/__tests__/mock_data/mockEarthResponses.js
  src/datasources/earth.js
Labels: feature

#50 Update tests to remove duplicate mockdata
  src/__tests__/mock_data/mockClientQueries.js
  src/__tests__/mock_data/mockResolverData.js
  src/__tests__/mock_data/mockSchemaResponses.js
  src/__tests__/resolvers.js
  src/resolvers.test.js
Labels: enhancement

#51 Update mock data to reduce duplication
  src/datasources/__tests__/mock_data/mockEarthResponses.js
Labels: enhancement

#53 Feature/52
  src/__tests__/resolvers.js
  src/datasources/__tests__/earth.js
  src/datasources/__tests__/mock_data/mockEarthResponses.js
  src/datasources/earth.js
  src/resolvers.js
  src/schema.js
Labels: feature

#55 Feature/#54
  README.md
  package.json
  src/datasources/__tests__/mapquest.js
  src/datasources/__tests__/mock_data/mockMapquestResponses.js
  src/datasources/mapquest.js
  src/index.js
  src/resolvers.js
  src/schema.js
Labels: feature

#59 Add code-climate coverage for tests
  .codeclimage.yml
  .github/workflows/ci.yml
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/favicon.png
  coverage/lcov-report/index.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov-report/trashpanda-be/database/dbConfig.js.html
  coverage/lcov-report/trashpanda-be/database/index.html
  coverage/lcov-report/trashpanda-be/database/migrations/20200131102323_initial.js.html
  coverage/lcov-report/trashpanda-be/database/migrations/20200131102336_special_instructions.js.html
  coverage/lcov-report/trashpanda-be/database/migrations/20200201103833_postal_code_implementation.js.html
  coverage/lcov-report/trashpanda-be/database/migrations/20200201105116_postal_codes_table.js.html
  coverage/lcov-report/trashpanda-be/database/migrations/index.html
  coverage/lcov-report/trashpanda-be/database/models/index.html
  coverage/lcov-report/trashpanda-be/database/models/materials-model.js.html
  coverage/lcov-report/trashpanda-be/database/models/postal_codes-model.js.html
  coverage/lcov-report/trashpanda-be/database/seeds/00-Cleanup.js.html
  coverage/lcov-report/trashpanda-be/database/seeds/01-Materials.js.html
  coverage/lcov-report/trashpanda-be/database/seeds/index.html
  coverage/lcov-report/trashpanda-be/index.html
  coverage/lcov-report/trashpanda-be/knexfile.js.html
  coverage/lcov-report/trashpanda-be/src/datasources/earth.js.html
  coverage/lcov-report/trashpanda-be/src/datasources/index.html
  coverage/lcov-report/trashpanda-be/src/datasources/mapquest.js.html
  coverage/lcov-report/trashpanda-be/src/index.html
  coverage/lcov-report/trashpanda-be/src/index.js.html
  coverage/lcov-report/trashpanda-be/src/resolvers.js.html
  coverage/lcov-report/trashpanda-be/src/schema.js.html
  coverage/lcov.info
  package.json
Labels: documentation

#63 Feature/62
  .gitignore
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/favicon.png
  coverage/lcov-report/index.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov-report/trashpanda-be/coverage/lcov-report/block-navigation.js.html
  coverage/lcov-report/trashpanda-be/coverage/lcov-report/index.html
  coverage/lcov-report/trashpanda-be/coverage/lcov-report/prettify.js.html
  coverage/lcov-report/trashpanda-be/coverage/lcov-report/sorter.js.html
  coverage/lcov-report/trashpanda-be/database/dbConfig.js.html
  coverage/lcov-report/trashpanda-be/database/index.html
  coverage/lcov-report/trashpanda-be/database/migrations/20200131102323_initial.js.html
  coverage/lcov-report/trashpanda-be/database/migrations/20200131102336_special_instructions.js.html
  coverage/lcov-report/trashpanda-be/database/migrations/20200201103833_postal_code_implementation.js.html
  coverage/lcov-report/trashpanda-be/database/migrations/20200201105116_postal_codes_table.js.html
  coverage/lcov-report/trashpanda-be/database/migrations/index.html
  coverage/lcov-report/trashpanda-be/database/models/index.html
  coverage/lcov-report/trashpanda-be/database/models/materials-model.js.html
  coverage/lcov-report/trashpanda-be/database/models/postal_codes-model.js.html
  coverage/lcov-report/trashpanda-be/database/seeds/00-Cleanup.js.html
  coverage/lcov-report/trashpanda-be/database/seeds/01-Materials.js.html
  coverage/lcov-report/trashpanda-be/database/seeds/index.html
  coverage/lcov-report/trashpanda-be/index.html
  coverage/lcov-report/trashpanda-be/knexfile.js.html
  coverage/lcov-report/trashpanda-be/src/datasources/earth.js.html
  coverage/lcov-report/trashpanda-be/src/datasources/index.html
  coverage/lcov-report/trashpanda-be/src/datasources/mapquest.js.html
  coverage/lcov-report/trashpanda-be/src/index.html
  coverage/lcov-report/trashpanda-be/src/index.js.html
  coverage/lcov-report/trashpanda-be/src/resolvers.js.html
  coverage/lcov-report/trashpanda-be/src/schema.js.html
  coverage/lcov.info
Labels: feature

#64 Feature/#56
  database/migrations/20200131102323_initial.js
  database/migrations/20200131102336_special_instructions.js
  database/migrations/20200213140924_category_images_table.js
  database/migrations/20200214101411_materials_images.js
  database/models/category_images-model.js
  database/seeds/01-Materials.js
  database/seeds/02-Category_Images.js
  src/datasources/__tests__/earth.js
  src/datasources/__tests__/mock_data/mockEarthResponses.js
  src/datasources/earth.js
  src/schema.js
Labels: feature

#66 Added new image links to missing/new categories/materials
  database/seeds/01-Materials.js
  database/seeds/02-Category_Images.js
Labels: feature

#69 Feature/67 img query
  src/datasources/__tests__/datascience.js
  src/datasources/__tests__/mock_data/mockDataScienceResponses.js
  src/datasources/datascience.js
  src/resolvers.js
  src/schema.js
Labels: feature

#70 Feature/58
  src/datasources/__tests__/mock_data/mockDataScienceResponses.js
  src/datasources/datascience.js
  src/resolvers.js
  src/schema.js
Labels: feature

#72 Update getCluster to return array of materials objects
  src/resolvers.js
Labels: feature

#73 Update cluster schema to return an array of Material
  src/schema.js
Labels: bug

#75 Added new image urls
  database/seeds/01-Materials.js
  database/seeds/02-Category_Images.js
Labels: feature

#77 Add multi-material by id query
  src/datasources/earth.js
  src/resolvers.js
  src/schema.js
Labels: feature
