Repository Lambda-School-Labs/trashpanda-be, pull requests merged in 2020-01, with the labels that each got.

#9 Feature/1
  .gitignore
  package-lock.json
  package.json
  src/index.js
  src/schema.js
Labels: feature

#13 Feature #2 dbConfig and knexfile
  .gitignore
  database/dbConfig.js
  knexfile.js
  package.json
Labels: feature

#14 Use port from environment vars, fallback to 4000
  src/index.js
Labels: bug

#12 Add code climate badge and update local server instructions
  README.md
Labels: documentation

#18 Add introspection flag for heroku
  src/index.js
Labels: bug

#19 Feature/7
  database/dbConfig.js
  src/datasources/earth.js
  src/index.js
  src/resolvers.js
  src/schema.js
Labels: feature

#20 getAllFamilies
  src/datasources/earth.js
  src/resolvers.js
  src/schema.js
Labels: feature

#21 Feature/3
  database/db_schema (1).png
  database/materials.db3
  database/migrations/zz-99_trashpanda.js
  knexfile.js
Labels: feature

#26 Feature/6
  .gitignore
  database/materials.db3
  database/models/materials-model.js
  src/datasources/earth.js
  src/index.js
  src/schema.js
Labels: feature

#27 Feature/11
  package-lock.json
  package.json
  src/index.js
  src/resolvers.test.js
Labels: feature

#33 Feature/4
  .gitignore
  database/migrations/20200131102323_initial.js
  database/migrations/20200131102336_special_instructions.js
  database/migrations/zz-99_trashpanda.js
  database/seeds/00-Materials.js
  database/seeds/01-Materials.js
Labels: feature

#36 getMaterial
  src/datasources/earth.js
  src/resolvers.js
  src/schema.js
Labels: feature
